const GOOGLE_SCRIPT_URL='https://script.google.com/macros/s/AKfycbxYs9ZEvfvly_HwWNubtrXCPquZ9Eyln4ZQkhU3qwgbuzjNgwyomFFvhrzV0DgiHE52Fw/exec';
const data={GENERAL_PASSWORD:'BIO2026',TEACHER_PIN:'2468'};
let teacherPinSession='';
const $=id=>document.getElementById(id);
function enter(){if($('pw').value===data.GENERAL_PASSWORD){$('login').classList.add('hidden');$('app').classList.remove('hidden')}else $('msg').textContent='Contraseña incorrecta.'}
function home(){$('home').classList.remove('hidden');$('student').classList.add('hidden');$('teacher').classList.add('hidden');$('physics').classList.add('hidden');if($('teacherDirectory'))$('teacherDirectory').classList.add('hidden')}
function openStudent(){home();$('home').classList.add('hidden');$('student').classList.remove('hidden');$('studentBox').innerHTML='<div class="box"><div class="eyebrow">BIOLOGÍA · CONSULTA EN LÍNEA</div><h2>Consulta tu evaluación</h2><p>Usa tu grupo, número de lista y PIN personal.</p><label>Grupo</label><select id="sg" onchange="nums()"><option>A</option><option>B</option><option>C</option></select><label>Número de lista</label><select id="sn"></select><label>PIN personal</label><input id="sp" maxlength="4" inputmode="numeric" autocomplete="off"><button class="primary" onclick="studentLogin()">Consultar</button><div id="sm" class="msg"></div></div>';nums()}
function nums(){$('sn').innerHTML=Array.from({length:$('sg').value==='A'?26:25},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}
async function studentLogin(){const g=$('sg').value,n=$('sn').value,p=$('sp').value.trim();$('sm').textContent='Consultando...';try{const u=GOOGLE_SCRIPT_URL+'?action=student&grupo='+encodeURIComponent(g)+'&num='+encodeURIComponent(n)+'&pin='+encodeURIComponent(p)+'&_='+Date.now();const r=await fetch(u,{cache:'no-store'});const d=await r.json();if(!d.ok){$('sm').textContent=d.error||'Datos incorrectos.';return}renderStudent(d)}catch(e){$('sm').textContent='No se pudo conectar con Google Sheets. Verifica tu conexión a internet.'}}
function renderStudent(d){const p=Number(d.porcentaje)||0;$('studentBox').innerHTML='<div class="box"><button class="back" onclick="openStudent()">← Regresar</button><div class="eyebrow">'+escapeHtml(d.alumno.grupo)+' · BIOLOGÍA · EN LÍNEA</div><h2>'+escapeHtml(d.alumno.nombre)+'</h2><div class="muted">Solo lectura · Información actualizada desde Google Sheets</div><div class="studentHead"><b>Avance</b><div class="percent">'+p+'%</div></div><div class="progress"><div class="bar" style="width:'+Math.min(p,100)+'%"></div></div>'+d.actividades.map(a=>'<div class="activity"><span>'+activityIcon(a.id)+'</span><div class="grow"><b>'+escapeHtml(a.name)+'</b><div class="muted">'+Number(a.weight)+'%</div></div><span>'+(a.realizada?'✅':'⬜')+'</span></div>').join('')+'</div>'}
function activityIcon(id){const icons={a1:'🧠',a2:'🔬',a3:'📘',a4:'🧫',a5:'🦠',a6:'📊',a7:'🤝'};return icons[id]||'📌'}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function teacher(){const pin=prompt('PIN docente:');if(pin!==data.TEACHER_PIN)return alert('PIN docente incorrecto.');teacherPinSession=pin;home();$('home').classList.add('hidden');$('teacher').classList.remove('hidden');$('table').innerHTML='<div class="box">Cargando evaluaciones desde Google Sheets...</div>';try{const r=await fetch(GOOGLE_SCRIPT_URL+'?action=all&teacherPin='+encodeURIComponent(pin)+'&_='+Date.now(),{cache:'no-store'});const d=await r.json();if(!d.ok)throw new Error(d.error||'Error');window.teacherData=d;renderTeacher()}catch(e){$('table').innerHTML='<div class="box msg">No se pudo conectar con Google Sheets. Verifica que la implementación de Apps Script esté activa.</div>'}}
function getActivities(){return (window.teacherData?.actividades||[]).filter(a=>String(a.Activa||'SI').toUpperCase()!=='NO')}
function renderTeacher(){const d=window.teacherData,g=$('tg')?.value||'A';$('teacher').querySelector('h2').innerHTML='Panel docente · Biología <span class="muted">· EN LÍNEA</span>';if(!$('tg').options.length)$('tg').innerHTML=['A','B','C'].map(x=>`<option>${x}</option>`).join('');$('tg').value=g;teacherTable()}
function teacherTable(){if(!window.teacherData)return;const g=$('tg').value;const students=window.teacherData.alumnos.filter(s=>String(s.Grupo_Codigo).toUpperCase()===g);const evals=window.teacherData.evaluaciones;const acts=getActivities();let html='<div class="tableWrap"><table class="table"><thead><tr><th>Alumno</th>'+acts.map(a=>'<th>'+escapeHtml(a.ID_Actividad)+'<br>'+Number(a.Porcentaje)+'%</th>').join('')+'<th>Total</th></tr></thead><tbody>';students.forEach(st=>{let total=0;html+='<tr><td>'+st.No_Lista+'. <b>'+escapeHtml(st.Alumno)+'</b></td>';acts.forEach(a=>{const ev=evals.find(x=>String(x.ID_Alumno)===String(st.ID_Alumno)&&String(x.ID_Actividad)===String(a.ID_Actividad));const done=ev&&String(ev.Realizada).toUpperCase()==='SI';if(done)total+=Number(a.Porcentaje)||0;html+='<td><input class="check" type="checkbox" '+(done?'checked':'')+' onchange="toggleRemote(\''+st.ID_Alumno+'\',\''+a.ID_Actividad+'\',this.checked)"></td>'});html+='<td class="total">'+total+'%</td></tr>'});html+='</tbody></table></div>';$('table').innerHTML=html}
async function toggleRemote(idAlumno,idActividad,checked){const box=$('table');box.style.opacity='.65';try{const u=GOOGLE_SCRIPT_URL+'?action=save&teacherPin='+encodeURIComponent(teacherPinSession)+'&idAlumno='+encodeURIComponent(idAlumno)+'&idActividad='+encodeURIComponent(idActividad)+'&realizada='+(checked?'SI':'NO')+'&_='+Date.now();const r=await fetch(u,{cache:'no-store'});const d=await r.json();if(!d.ok)throw new Error(d.error||'No se guardó');let ev=window.teacherData.evaluaciones.find(x=>String(x.ID_Alumno)===String(idAlumno)&&String(x.ID_Actividad)===String(idActividad));if(ev)ev.Realizada=checked?'SI':'NO';else window.teacherData.evaluaciones.push({ID_Alumno:idAlumno,ID_Actividad:idActividad,Realizada:checked?'SI':'NO',Porcentaje_Obtenido:0,Ultima_Actualizacion:new Date().toISOString()});teacherTable()}catch(e){alert('No se pudo guardar en Google Sheets.');teacherTable()}finally{box.style.opacity='1'}}
if('serviceWorker' in navigator && location.protocol==='https:'){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
